$MODEL AcubeSAT_Model
# 
# template file: Template.tpl
# ESATAN-TMS 2020, run date 21:55 Wed 16 Sep 2020
# Model name: AcubeSAT_Model        Analysis case: Cold_Nominal_TIME_STEP_005
#
  $LOCALS
  # GENCODE LOCALS - DO NOT REMOVE 
#
  $NODES
  # GENCODE NODES - DO NOT REMOVE 
#
  $CONDUCTORS
  # GENCODE CONDUCTORS - DO NOT REMOVE 
#
  $CONSTANTS
  # GENCODE CONSTANTS - DO NOT REMOVE 
#
  $ARRAYS
  # GENCODE ARRAYS - DO NOT REMOVE 
#
  $EVENTS
  # GENCODE EVENTS - DO NOT REMOVE 
#
  $SUBROUTINES
  # GENCODE SUBROUTINES - DO NOT REMOVE 
C
  $INITIAL
      GENMOR
  # GENCODE BOUNDARY_CONDS - DO NOT REMOVE 
  # GENCODE INITIAL - DO NOT REMOVE 
C
  $EXECUTION
C
      NLOOP=100
      RELXCA=0.01
      CALL SOLVFM
C
C
      TIMEND=5675
      OUTINT=1.0
      NLOOP=100
      RELXCA=0.01
      DTIMEI=0.05
      CALL SOLCYC('SLCRNC',0.05D0,0.01D0,5675D0,60,' ','ALL')
C
      CALL SLCRNC
C


C
  $VARIABLES1
  # GENCODE VARIABLES1 - DO NOT REMOVE 
C
  $VARIABLES2
  # GENCODE VARIABLES2 - DO NOT REMOVE 
C
  $OUTPUTS
      CALL PRNDTB(' ', 'L, T, QS, QE, QA, QI, C', CURRENT)
C
      CALL DMPTMD(' ', 'NODES, CONDUCTORS, CONSTANTS', CURRENT, ' ')

  # GENCODE OUTPUTS - DO NOT REMOVE 
C
$ENDMODEL AcubeSAT_Model
